ITK.Web/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace ITK.Web.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

ITK.Web/Pages/Explore/New.cshtml.cs
using ITK.DataStore.EFCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ITK.Web.Pages.Explore
{
    public class NewModel : PageModel
    {
        public FilterType ParamFilterType { get; set; }

        private readonly ILogger<NewModel> _logger;

        public NewModel(ILogger<NewModel> logger)
        {
            _logger = logger;
        }

        public void OnGet(FilterType? filterType)
        {
            if (filterType == null)
            {
                //  Default
                ParamFilterType = FilterType.All;
            }
            else
            {
                ParamFilterType = filterType.Value;
            }
        }
    }
}

ITK.Web/Pages/Explore/Popular.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ITK.Web.Pages.Explore
{
    public class PopularModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

ITK.Web/Pages/Index.cshtml.cs
using ITK.Core;
using ITK.DataStore.EFCore;
using ITK.UseCases.Interfaces;
using ITK.UseCases.Utilities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace ITK.Web.Pages
{
    public class IndexModel : PageModel
    {
        public int? PageIndex { get; set; }
        public IndexModel()
        {   
        }
        

        public void OnGet(int? pageIndex)
        {
            PageIndex = pageIndex;
        }
    }
}

ITK.Web/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ITK.Web.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

ITK.Web/Pages/Shared/Components/ProductsGrid/Default.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ITK.Web.Pages.Components.Products
{
    public class DefaultModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

ITK.Web/Pages/Shared/_Cart.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ITK.Web.Pages.Shared
{
    public class _CartModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

ITK.Web/Pages/Shared/_Footer.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ITK.Web.Pages.Shared
{
    public class _FooterModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

ITK.Web/Pages/Shared/_Header.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ITK.Web.Pages.Shared
{
    public class _HeaderModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

ITK.Web/Pages/Shared/_NewSection.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ITK.Web.Pages.Shared
{
    public class _NewSectionModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

ITK.Web/Pages/Shared/_ProductsGrid.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ITK.Web.Pages.Shared
{
    public class _ProductsGridModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

ITK.Web/Pages/Shared/_StepsSection.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ITK.Web.Pages.Shared
{
    public class _StepsSectionModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

ITK.Web/Pages/Shared/_SwiperSlide.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ITK.Web.Pages.Shared
{
    public class _SwiperSlideModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

ITK.Web/ViewComponents/ProductsGridViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using ITK.Core;
using ITK.UseCases.Utilities;
using ITK.UseCases.Products;
using ITK.Web.Pages;
using ITK.UseCases.Interfaces;
using Microsoft.EntityFrameworkCore;

namespace ITK.Web.ViewComponents
{
    //  This is the code part of the ProductsGridViewComponent.It makes use of
    //  the ViewCategoriesUseCase via dependency injection system to resolve
    //  the implementation of IViewCategoryUseCase which procided dependency
    //  injection of ICategoryRepositorywhich and is injected into the constructor
    //  of the view component class. The InvokeAsync method obtains a
    //  List<Category> from the service and passes it to the view.
    [ViewComponent]
    public class ProductsGridViewComponent : ViewComponent
    {
        private IViewProductsByFilterUseCase ViewProductsByFilterUseCase { get; }
        private readonly ILogger<IndexModel> _logger;
        public PaginatedList<Product> Products { get; set; }
        private IConfiguration Configuration { get; }
        public int? PageIndex { get; set; }

        public ProductsGridViewComponent(
            IConfiguration configuration, 
            ILogger<IndexModel> logger,
            IViewProductsByFilterUseCase viewProductsByFilterUseCase)
        {
            Configuration = configuration;
            _logger = logger;
            ViewProductsByFilterUseCase = viewProductsByFilterUseCase;
        }

        public async Task<IViewComponentResult> InvokeAsync(
            int? pageIndex
            )
        {
            PageIndex = pageIndex;
            await GetDataAsync();

            return View(Products);
        }

        public async Task GetDataAsync()
        {
            if (PageIndex == null || !PageIndex.HasValue)
            {
                PageIndex = 1;
            }

            var pageSize = Configuration.GetValue("PageSize", 15);
            Products = await PaginatedList<Product>.CreateAsync(
                ViewProductsByFilterUseCase.Execute().Products.AsNoTracking(),
                PageIndex ?? 1, pageSize
                );
        }
    }
}

ITK.Web/Pages/Explore/New.cshtml
@page "{filter?}"
@model ITK.Web.Pages.Explore.NewModel
@{
    ViewData["Title"] = "Discover our newest products";
}

<section class="home container section">

    <div class="products__grid-filter-wrap grid">
        <div class="product__grid-tabs-wrap">
            <div class="grid__tab-item active">
                <a asp-page="./Index">All</a>
            </div>
            <div class="grid__tab-item">
                <a asp-page="/Explore/New" asp-route-filterType="@FilterType.All">New</a>
            </div>
            <div class="grid__tab-item">
                <a asp-page="/Explore/Popular">Popular</a>
            </div>

        </div>
        <div class="product__price-filter">
            <div class="product__price-filter-wrap">
                <a class="price__filter-item active" asp-page="/Explore/New" asp-route-filterType="@FilterType.All">All</a>
                <a class="price__filter-item" asp-page="/Explore/New" asp-route-filterType="@FilterType.LessThan50">Under £50</a>
                <a class="price__filter-item" asp-page="/Explore/New" asp-route-filterType="@FilterType.LestThan100">Under £100</a>
                <a class="price__filter-item" asp-page="/Explore/New" asp-route-filterType="@FilterType.LessThan250">Under £250</a>
            </div>
        </div>
    </div>

    @await Component.InvokeAsync("ProductsGrid", new {
    })
</section>

ITK.Web/Pages/Explore/Popular.cshtml
@page
@model ITK.Web.Pages.Explore.PopularModel
@{
    ViewData["Title"] = "Check out our most popular products";
}

<section class="home container section">
    <h1>Popular items hre</h1>
</section>

ITK.Web/Pages/Index.cshtml
@page "{pageIndex:int?}"
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<section class="home container section">

<div class="products__grid-filter-wrap grid">
    <div class="product__grid-tabs-wrap">
        <div class="grid__tab-item active">
            <a class="navbar-brand" asp-page="./Index">All</a>
        </div>
        <div class="grid__tab-item">
            <a asp-page="/Explore/New">New</a>
        </div>
        <div class="grid__tab-item">
            <a asp-page="/Explore/Popular">Popular</a>
        </div>
    </div>
</div>

    @await Component.InvokeAsync("ProductsGrid", new {
        pageIndex = Model.PageIndex
    })

    <ul class="pagination">
        <li class="page-item">
            <div class="page-link" href="#" aria-label="Previous" onclick="PrevPageAsync">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
            </div>
        </li>
    </ul>

</section>
<!--=============== HOME ===============-->
<section class="home container">
    <partial name="_SwiperSlide" />
</section>

ITK.Web/Pages/Shared/Components/ProductsGrid/Default.cshtml
@using System.Globalization
@model ITK.UseCases.Utilities.PaginatedList<Product>
@{
    if(Model != null){
        <div class="products__grid grid">
            @foreach (var item in Model)
            {
                <div class="products__grid-gridItem-wrap">
                        <div class="products__grid-gridItem-header">
                            <div class="gridItem__header-button">
                                <a href="#" class="gridItem__header-link">
                                    <div class="gridItem__header-link-wrap button__icon">
                                        £ @String.Format(CultureInfo.InvariantCulture,"{0:0.00}", @item.Price)
                                        <i class="bx bx-right-arrow-alt"></i>
                                    </div>                    
                                </a>
                            </div>
                        </div>
        
                        <div class="products__grid-gridItem-img-wrap">
                            <img class="product__grid-product-img" src="~/img/products/@item.Image" />
                        </div>
                        <div class="products_grid-gridItem-details">
                            <div class="gridItem__details-name">
                                @StringExtensions.ShortenAndFormatText(item.Title, 50).ToString()
                            </div>
                        </div>
                    </div>
            }
        </div>

        <ul class="pagination">
            @{
                // Current page should never go below 1
                if(Model.CurrentPage > 1)
                {
                    var currentPage = (Model.CurrentPage);
                    <li class="page-item">
                        <a class="page-item active" asp-page="./Index" asp-route-pageIndex="@currentPage--">
                                <span aria-hidden="true">&laquo;</span>
                                <span class="sr-only">Previous</span>
                        </a>
                    </li>
                }
                else
                {
                    <li class="page-item">
                        <span aria-hidden="true">&laquo;</span>
                        <span class="sr-only">Previous</span>
                    </li>
                }
            }

            @for (int i = Model.CurrentPage - 3; i < Model.CurrentPage + 3; i++)
            {
                if(i > 0 && i <= Model.TotalPages)
                {
                    //  set active page
                    if(i == Model.CurrentPage)
                    {
                        <a class="page-item active" asp-page="./Index" asp-route-pageIndex="@i">@i</a>
                    }
                    else
                    {
                        <a class="page-item" asp-page="./Index" asp-route-pageIndex="@i">@i</a>
                    }
                }
            }
            @if(Model.CurrentPage < Model.TotalPages)
            {
                // so long as current page <= total pages
                var nextage = Model.CurrentPage;
                nextage++;
                <li class="page-item">
                    <a class="page-item" asp-page="./Index" asp-route-pageIndex="@nextage">
                        <span aria-hidden="true">&raquo;</span>
                        <span class="sr-only">Next</span>
                    </a>
                </li>
            }
            else
            {
                <li class="page-item disabled">
                    <div class="page-link" href="#" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                        <span class="sr-only">Next</span>
                    </div>
                </li>
            }
        </ul>

        <div class="products__grid-more-wrap">
            <p>MORE</p>
        </div>
    }
    else
    {
        <h1>Loading</h1>
    }
}

ITK.Web/Pages/Shared/_Cart.cshtml
<!--=============== CART ===============-->
<div class="cart" id="cart">
	<i class="bx bx-x cart__close"></i>

	<h2 class="cart__title-center">
		My Cart
	</h2>

	<div class="cart__container">
		<article class="cart__card">
			<div class="cart__box">
				<img src="img/products/Eva-Solo-Dzbanek-Kettle-Silver.jpg" class="cart__img"/>
			</div>
			<div class="cart__details">
				<h3 class="cart__title">Eva Solo - Dzbanek Termiczny Kettle - Silver</h3>
				<span class="cart__price">£75.83</span>

				<div class="cart__amount">
					<div class="cart__amount-content">
						<span class="cart__amount-box">
							<i class="bx bx-minus"></i>
						</span>

						<span class="cart__amount-number">1</span>

						<span class="cart__amount-box">
							<i class="bx bx-plus"></i>
						</span>
					</div>
					<i class="bx bx-trash-alt cart__amount-trash"></i>
				</div>
			</div>
		</article>
		<article class="cart__card">
			<div class="cart__box">
				<img src="img/assets/cart-2.png" class="cart__img" />
			</div>
			<div class="cart__details">
				<h3 class="cart__title">Cardigan Hoodie</h3>
				<span class="cart__price">£16</span>

				<div class="cart_amount">
					<div class="cart__amount-content">
						<span class="cart__amount-box">
							<i class="bx bx-minus"></i>
						</span>

						<span class="cart__amount-number">1</span>

						<span class="cart__amount-box">
							<i class="bx bx-plus"></i>
						</span>
					</div>
					<i class="bx bx-trash-alt cart__amount-trash"></i>
				</div>
			</div>
		</article>
		<article class="cart__card">
			<div class="cart__box">
				<img src="img/assets/cart-3.png" class="cart__img" />
			</div>
			<div class="cart__details">
				<h3 class="cart__title">Cartoon</h3>
				<span class="cart__price">£10</span>

				<div class="cart_amount">
					<div class="cart__amount-content">
						<span class="cart__amount-box">
							<i class="bx bx-minus"></i>
						</span>

						<span class="cart__amount-number">1</span>

						<span class="cart__amount-box">
							<i class="bx bx-plus"></i>
						</span>
					</div>
					<i class="bx bx-trash-alt cart__amount-trash"></i>
				</div>
			</div>
		</article>
	</div>

	<div class="cart__prices">
		<span class="cart__prices-item">3 item(s)</span>
		<span class="cart__prices-total">£34.56</span>
	</div>
</div>

ITK.Web/Pages/Shared/_Footer.cshtml
<!--=============== FOOTER ===============-->
<footer class="footer">
	<div class="footer__container container flex">
		<!-- FOOTER CONTENT 1 -->
		<div class="footer__content">
			<a href="#" class="footer__logo">
				<i class="bx bxs-shopping-bags footer__logo-icon">InTheKitchen</i>
			</a>
			<p class="footer__description">All the best goodies for your kitchen</p>
		</div>
		<div class="footer__content">
			<a href="#" class="footer__link">Home</a>
			<a href="#" class="footer__link">Favorites</a>
			<a href="#" class="footer__link">Basket</a>
		</div>
		<div class="footer__content">
			<a href="#" class="footer__social-link"><i class="bx bxl-facebook"></i></a>
			<a href="#" class="footer__social-link"><i class="bx bxl-instagram-alt"></i></a>
			<a href="#" class="footer__social-link"><i class="bx bxl-twitter"></i></a>
		</div>	
	</div>
</footer>

ITK.Web/Pages/Shared/_Header.cshtml
<header class="header" id="header">
    <nav class="nav container">
        <a href="#" class="nav__logo">
            <i class="bx bxs-shopping-bags nav__logo-icon">
                InTheKitchen
            </i>
        </a>

        <div class="nav__menu" id="nav-menu">
            <ul class="nav__list">
                <li class="nav__item">
                    <a href="#" class="nav__link active-link">Home</a>
                </li>
                <li class="nav__item">
                    <a href="#" class="nav__link">Shop</a>
                </li>
                <li class="nav__item">
                    <a href="#" class="nav__link">Cart</a>
                </li>
                <li class="nav__item">
                    <a href="#" class="nav__link">Blog</a>
                </li>
                <li class="nav__item">
                    <a href="#" class="nav__link">FAQ's'</a>
                </li>
                <li class="nav__item">
                    <a href="#" class="nav__link">Contacts</a>
                </li>
            </ul>
        </div>

        <div class="nav__btns">
            <div class="login__toggle" id="Login-toggle">
                <i class="bx bx-user"></i>
            </div>
            <div class="nav_shop" id="cart-shop">
                <i class="bx bx-shopping-bag"></i>
            </div>
            <div class="nav__toggle" id="nav-toggle">
                <i class="bx bx-grid-alt"></i>
            </div>
        </div>
    </nav>
</header>

ITK.Web/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="All the best gadgets and goodies for your kitchen" />
    <title>InTheKitchen.com - @ViewData["Title"]</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;500;600;800&display=swap" rel="stylesheet">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="assets/css/colors/color-1.css">
    <link rel="stylesheet" href="~/lib/swiper/css/swiper-bundle.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ITK.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <partial name="_Header" />
    <partial name="_Cart" />
    <partial name="_LoginPartial" />

    <!--=============== MAIN ===============-->
    <main class="main">
        @RenderBody()
    </main>

    <partial name ="_Footer" />

    <!--=============== SCROLL UP ===============-->
    <!--=============== STYLE SWITCHER ===============-->
    <!--=============== SWIPER JS ===============-->
     <script src="~/lib/swiper/js/swiper-bundle.min.js" asp-append-version="true"></script>

    <!--=============== JS ===============-->
    <script src="https://unpkg.com/boxicons@2.1.4/dist/boxicons.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ITK.Web/Pages/Shared/_NavBar.cshtml
<div class="container">
	<div class="item">
		<div class="callButton">
			<img src="callButton.png" />
		</div>
		<div class="texts">
			<div class="text">Order Now</div>
			<div class="text">123-456</div>
		</div>
		<div class="Item"></div>
		<div class="Item"></div>
	</div>
</div>

ITK.Web/Pages/Shared/_NewSection.cshtml
<!--=============== NEW ARRIVALS ===============-->
<section class="new section">
	<h2 class="section__title">New Arrivals</h2>

	<div class="new__container container">
		<div class="swiper new-swiper">
			<div class="swiper-wrapper">
				<!-- New content item 1 -->
				<div class="new__content swiper-slide">
					<div class="new__tag">New</div>
					<img src="~/img/products/Dansk-Kobenstyle-White-Casserole-Dish.jpg" class="new__img" alt="" />
					<h3 class="new__title">Dansk - Kobenstyle White Casserole Dish</h3>
					<span class="new__subtitle">Acessory</span>

					<div class="new__prices">
						<span class="new__price">£67.89</span>
						<span class="new__discount">£67.89</span>
					</div>

					<a href="#" class="button new__button">
						<i class="bx bx-cart-alt new__icon"></i>
					</a>					
				</div>
				<!-- New content item 1 -->
				<!-- New content item 2 -->
				<div class="new__content swiper-slide">
					<div class="new__tag">New</div>
					<img src="~/img/products/Dansk-Kobenstyle-White-Casserole-Dish.jpg" class="new__img" alt="" />
					<h3 class="new__title">Dansk - Kobenstyle White Casserole Dish</h3>
					<span class="new__subtitle">Acessory</span>

					<div class="new__prices">
						<span class="new__price">£67.89</span>
						<span class="new__discount">£67.89</span>
					</div>

					<a href="#" class="button new__button">
						<i class="bx bx-cart-alt new__icon"></i>
					</a>
				</div>
				<!-- New content item 2 -->
				<!-- New content item 3 -->
				<div class="new__content swiper-slide">
					<div class="new__tag">New</div>
					<img src="~/img/products/Dansk-Kobenstyle-White-Casserole-Dish.jpg" class="new__img" alt="" />
					<h3 class="new__title">Dansk - Kobenstyle White Casserole Dish</h3>
					<span class="new__subtitle">Acessory</span>

					<div class="new__prices">
						<span class="new__price">£67.89</span>
						<span class="new__discount">£67.89</span>
					</div>

					<a href="#" class="button new__button">
						<i class="bx bx-cart-alt new__icon"></i>
					</a>					
				</div>
				<!-- New content item 3 -->
				<!-- New content item 4 -->
				<div class="new__content swiper-slide">
					<div class="new__tag">New</div>
					<img src="~/img/products/Dansk-Kobenstyle-White-Casserole-Dish.jpg" class="new__img" alt="" />
					<h3 class="new__title">Dansk - Kobenstyle White Casserole Dish</h3>
					<span class="new__subtitle">Acessory</span>

					<div class="new__prices">
						<span class="new__price">£67.89</span>
						<span class="new__discount">£67.89</span>
					</div>

					<a href="#" class="button new__button">
						<i class="bx bx-cart-alt new__icon"></i>
					</a>
				</div>
				<!-- New content item 4 -->
				<!-- New content item 5 -->
				<div class="new__content swiper-slide">
					<div class="new__tag">New</div>
					<img src="~/img/products/Dansk-Kobenstyle-White-Casserole-Dish.jpg" class="new__img" alt="" />
					<h3 class="new__title">Dansk - Kobenstyle White Casserole Dish</h3>
					<span class="new__subtitle">Acessory</span>

					<div class="new__prices">
						<span class="new__price">£67.89</span>
						<span class="new__discount">£67.89</span>
					</div>

					<a href="#" class="button new__button">
						<i class="bx bx-cart-alt new__icon"></i>
					</a>
				</div>
				<!-- New content item 5 -->
			</div>
		</div>
	</div>
</section>

ITK.Web/Pages/Shared/_ProductsGrid.cshtml
<section class="grid container">
	<div class"products__grid-subnav">
		<a class="products__grid-nav-item" href="#">CategoryItem</a>
	</div>
	<div class="discount__container container grid">

	</div>
</section>

ITK.Web/Pages/Shared/_StepsSection.cshtml
<!--=============== STEPS ===============-->
<section class="steps section container">
	<div class="steps__bg">
		<h2 class="section__title">How to order </h2>

		<div class="steps__container grid">
			<!-- Step 1 -->
			<div class="steps__card">
				<div class="steps__card-number">01</div>
				<h3 class="steps__card-title">Choose Products</h3>
				<p class="steps__card-description">
					We have several products you can choose from.
				</p>
			</div>
			<!-- Step 1 ends -->
			<!-- Step 2 -->
			<div class="steps__card">
				<div class="steps__card-number">02</div>
				<h3 class="steps__card-title">Place an order</h3>
				<p class="steps__card-description">
					Once ordered, you item is shipped the next day (Monday to Friday).
				</p>
			</div>
			<!-- Step 2 ends -->
			<!-- Step 3 -->
			<div class="steps__card">
				<div class="steps__card-number">02</div>
				<h3 class="steps__card-title">Place an order</h3>
				<p class="steps__card-description">
					Our delevery process, can be tracked online, right up to it's
					delivered to you door.
				</p>
			</div>
			<!-- Step 3 ends -->
		</div>
	</div>
</section>

ITK.Web/Pages/Shared/_SwiperSlide.cshtml
<div class="swiper home-swiper">
    <!-- swiper-wrapper -->
    <div class="swiper-wrapper">

        <!-- swiper item 1 -->
        <section class="swiper-slide">
            <div class="home__content grid">
                <div class="home__group">
                    <div class="slide__item-details-brief">
                        <div class="slide__product_img_card">
                            <img src="/img/products/Sage-Barista-Express-Espresso-Machine.jpg" class="home__img" alt="" />
                        </div>
                        <div class="home__indicator"></div>

                        <div class="home__details-img">
                            <h4 class="home__details-title">Sage Barista Express Espresso Machine</h4>
                            <span class="home__details-subtitle">£789.00</span>
                        </div>
                    </div>

                </div>


                <div class="home__data">
                    <h3 class="home__subtitle">#3 Trending Item</h3>
                    <h1 class="home__title">Original <br />IS NEVER <br /> FINISHED! </h1>
                    <p class="home__description">
                        Sage Barista Express Espresso Machine - Espresso and Coffee Maker, Bean to
                        Cup Coffee Machine,Brushed Stainless Steel
                    </p>

                    <div class="home__buttons">
                        <a href="#" class="button">Buy Now</a>
                        <a href="#" class="button--link button--flex">
                            View Details
                            <i class="bx bx-right-arrow-alt button__icon"></i>
                        </a>
                    </div>
                </div>
            </div>

        </section>
        <!-- swiper item 1 ends -->
        <!-- swiper item 2 -->
        <section class="swiper-slide">
            <div class="home__content grid">
                <div class="home__group">
                    <div class="slide__item-details-brief">
                        <div class="slide__product_img_card">
                            <img src="/img/products/EVA-SOLO-Citrus-Press-Green.jpg" class="home__img" alt="" />
                        </div>
                        <div class="home__indicator"></div>

                        <div class="home__details-img">
                            <h4 class="home__details-title">EVA SOLO Citrus Press - Green</h4>
                            <span class="home__details-subtitle">£14.98</span>
                        </div>
                    </div>

                </div>


                <div class="home__data">
                    <h3 class="home__subtitle">#3 Trending Item</h3>
                    <h1 class="home__title">Original <br />IS NEVER <br /> FINISHED! </h1>
                    <p class="home__description">
                        Sage Barista Express Espresso Machine - Espresso and Coffee Maker, Bean to
                        Cup Coffee Machine,Brushed Stainless Steel
                    </p>

                    <div class="home__buttons">
                        <a href="#" class="button">Buy Now</a>
                        <a href="#" class="button--link button--flex">
                            View Details
                            <i class="bx bx-right-arrow-alt button__icon"></i>
                        </a>
                    </div>
                </div>
            </div>

        </section>
        <!-- swiper item 2 ends -->
    </div>

    <div class="swiper-pagination"></div>
    <!-- swiper-wrapper ends -->
</div>